<?php

return array('categoryes' =>'Категории',
	         'category' =>'Категория',
	         'new_products' =>'Новые товары',
	         'curency'=>'руб.',
	         'add_to_card'=>'добавить в корзину',
	         'detail'=>'детали',
	         'cart'=>'Корзина',
	          'catalog'=>'Каталог товаров',
	          'home'=>'Главная',
	          'all_products'=>'Все товары',
	          'all_catergores'=>'Все категории',
	          'all_orders'=>'Все заказы',
	          'recomended'=>'Рекомендуемые',
	          'price'=>'Цена',
	          'availability'=>'Наличие',
	          'model'=>'Модель',
	          'manufactured'=>'Производитель',
	          'quantity'=>'Количество',
	          'in_stock'=>'есть на складе',
	          'out_stock'=>'нет на складе',
	          'add_to_cart'=>'Добавить в корзину',
	          'product_description'=>'Описание',
	          'registration'=>'Регистрация',
	          'name'=>'Имя',
	          'email'=>'Eлектронная почта',
	          'pass'=>'Пароль',
	          'submit'=>'Отправить',
	            'reset'=>'Сброс',
	            'incorect_name'=>'Неправильное имя',
	            'incorect_pass'=>'Возможно короткий пароль',
	            'incorect_email'=>'Некоректный емейл введите в правильном формате ',
	            'incorect_register'=>'Пользователь не зарегистрирован повторите попытку',
	            'corect_register'=>'Пользователь удачно зарегистрирован',
	            'cab'=>'Личный кабинет',
	            'edit_data'=>'Редактировать данные',
	            'shop_list'=>'Список покупок',
	            'user_login'=>'Вход',
	            'enter_site'=>'Вход на сайт',
	            'present_user'=>'Пользователь существует',
	            'exit'=>'Выход',
	            'input_new_pass'=>'Введите новый пароль',
	            'input_new_name'=>'Введите новое имя',
	            'update_data_user'=>'Данные об пользователе обновлены',
	            'edit'=>'Редактировать',
	            'apply'=>'Применить',
	            'contacts'=>'Контакты',
	            'call_back'=>'Форма обратной связи',
	            'quest'=>'Задайте вопрос',
	            'message'=>'Сообщение',
	            'send'=>'отправить',
	            'send_mess'=>'Письмо отправилено',
	             'admin_panel'=>'Админ панель',
	             'edit_products'=>'Редактор товаров',
	             'edit_gategories'=>'Редактор категорий',
	             'edit_orders'=>'Редактор заказов',
<<<<<<< HEAD
	             'delete'=>'Удалить',
=======
				 'cart_submit'=>'Оформить заказ',
				 'cart_submit_all'=>'Оформить все заказы'
>>>>>>> 4347cbc27568a3527c12249e9ef77bc5d8c1807b



	           );


  ?>